NCSC-NL/log4shell

software/README.md
The Debian security tracker requires a bit of inside knowledge to read.
If something is fixed in "bullseye-security", it is fixed (DSA issued, packages available), even if bullseye is listed as vulnerable (this refers to the main archive). For any user, it's fixed.
strecth, buster, bullseye are the supported (old)stable releases. bookworm is Debian testing and does not get security support/is not a stable release yet.
Thijs Kinkhorst
SURFcert & Debian Security Team
=> Debian has fixed all current supported releases

software/README.md
Email Security | Impacted | 
After review, version 10.x appears to be impacted by CVE-2021-44228. SonicWall is reading a HotFix to remediate the issue, which will be released shortly.
Source https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2021-0032
=> Changed SonicWall EMS -not vuln -> Vulnerable

software/README.md
Topicus KeyHub is an IAM application used by a number of governmental and non-governmental organisations in the Netherlands.
=> Adds Topicus KeyHub to the list of software

software/README.md
Ubiquiti have since release, published a security bulletin containing all relevant information
This commit changes the link to the security bulletin
=> Updated link of Ubiquiti Unifi

software/README.md
log4j-core has only Maven scope 'test' so it's not part of the end product.
=> Fix Azure Data Lake Client - not vuln

software/README.md
It turns out that ILMT application itself is NOT vulnerable/impacted as it does not use the problematic log4j2 library. The subject log4j2 library is only used by VM Manager (VMMAN) tool module - however, note the VMMAN tool cannot be accessed remotely, so there is no way to exploit this vulnerability from any remote location:
https://www.ibm.com/docs/en/license-metric-tool?topic=security-flow-data
In order to be on the safe side, ILMT development suggest to upgrade all VM Manager (VMMAN) tool instances to the latest version - 9.2.26. It is meant to be published soon.
Meanwhile, the following technote contains all the details/procedures to mitigate this VM Manager (VMMAN) tool vulnerability as of now:
https://www.ibm.com/support/pages/node/6525762
=> Added IBM ILMT / VM Manager Tool 

software/README.md
Red Hat Build of Quarkus was previously marked as affected but that was not true.
It have been updated on https://access.redhat.com/security/cve/cve-2021-44228.
=> Update Red Hat Build of Quarkus

software/README.md
Add GitHub Enterprise Server to Software List
Affected versions: <3.3.1, <3.2.6, <3.1.14, <3.0.22
Source: https://github.blog/2021-12-13-githubs-response-to-log4j-vulnerability-cve-2021-44228/
=> GitHub Enterprise Server

software/README.md
Some markdown links were not written correctly for oracle and cisco, square brackets were missing or there were spaces between square and round brackets.
=> Fixed Markdown Links

mitigation/README.md
This PR explains the limitations of using the regular expression to detect presence of log4shell vulnerability in logs, and introduces a new alternative detection method.
The data is based on SK-CERT internal research of the vulnerability.
=> Update regex info - add caveats and other detection methods

software/README.md
- Status: not vulnerable
- Version: all versions
- Links: http://geoserver.org/announcements/2021/12/13/logj4-rce-statement.html
=> GeoServer not vulnerable

software/README.md
I believe that can be helpful when triaging vulnerabilities.
directory
=> Added a note on GrayLog exploitation direction

software/README.md
Added ISL Online to list based on: https://blog.islonline.com/2021/12/13/isl-online-is-not-affected-by-log4shell-vulnerability/
directory
=> Added ISL Online to not vuln

software/README.md
Updated SailPoint entry based on its updated statement: vulnerability can be mitigated by introducing a JVM system property (log4j2.formatMsgNoLookups to true) to all IdentityIQ runtime environments
=> SailPoint IdentityIQ 8.0 or later workaround

software/README.md
Apache don't appear to have made the upcoming fix in Solr 8.11.1 available yet, they just say it will be fixed in 8.11.1, but the most recent version people can download is 8.11.0, which is still vulnerable, but with mitigation steps that can be taken, hence until the fix is released I don't think this should be classed as "fixed".
From https://solr.apache.org/security.html#apache-solr-affected-by-apache-log4j-cve-2021-44228
"Upgrade to Solr 8.11.1 or greater (when available)" - and at present it doesn't appear to be available
Status Fix? …
=> Solr status should be workaround, not fix

mitigation/README.md, software/README.md
Gravwell has published a blog post stating that Gravwell products are not vulnerable. Since Gravwell is frequently used for network log aggregation, the blog post also includes some example queries to hunt for scanning attempts; I've therefore added a link in the mitigation file too.
=> Add Gravwell

software/README.md
There is a typo in the table for Forescout, it shows as soruce instead of source
directory
=> Typo in the Table for Forescout

software/README.md
Fixed the Typo in Cisco Identity Services Engine Vendor Statement Link
=> Fixed Cisco ISE Link Typo

software/README.md
Has always used 1.x
Thijs Kinkhorst / SURFcert
=> Update Apache Spark to Not Vuln

software/README.md
jPOS doesn't use log4j but just in case your jPOS based application uses it, our 2 cents.
=> Add jPOS ISO/Bridge status

software/README.md
Amazon have confirmed that "all Amazon API Gateway hosts have been patched to mitigate the Log4j issue" as per the linked document, so updated comment to reflect that
https://aws.amazon.com/security/security-bulletins/AWS-2021-006/
=> AWS API Gateway changed to reflect all patched

software/README.md
Added Amazon ElastiCache status from the Amazon security bulletin regarding the vulnerability
https://aws.amazon.com/security/security-bulletins/AWS-2021-006/
=> Added Amazon ElastiCache status

software/README.md
Added status for AWS Step Functions as fixed, taken from the AWS security bulletin - https://aws.amazon.com/security/security-bulletins/AWS-2021-006/
=> Added AWS Step Functions

software/README.md
Taken from AWS security bulletin https://aws.amazon.com/security/security-bulletins/AWS-2021-006/
This has been fixed in the lastest OpenSearch release, but isn't done automatically in the background, customers will need to update their clusters to the fixed version to mitigate this, so made that clear in the notes.
=> Updated version for OpenSearch and fix notes

software/README.md
esri provided scripts which remove JndiLookup class for vulnerable versions
directory
=> esri provided scripts which remove JndiLookup class, updated status to workaround

software/README.md
add Extensis | Universal Type Server not Vulnerable after updating to 7.06
directory
=> Extensis | Universal Type Server

software/README.md
Neighter are vuln
Beyondcompare makes the remark in the footer of there site.
directory
=> Add Beyond Compare and Bitwarden not vuln

software/README.md
Added Specops Software products as not vulnerable according to Vendor Statement: https://specopssoft.com/blog/apache-log4j-vulnerability
=> Added Specops Software

software/README.md
I've updated the Apache Flink fix versions to 1.14.2 / 1.13.5 / 1.12.7 / 1.11.6 since these versions contain fixes for all the Log4j CVEs (both CVE-2021-44228 and CVE-2021-45046)
=> Updating Apache Flink to point to the latest version

software/README.md
Added entry to `software/README.md` indicating that CockroachDB is not affected by the log4j vulnerability.
=> Add status of CockroachDB

software/README.md
- Status: updated to log4j 2.16.0
- Version: fix #30241
- Links: https://www.jetbrains.com/help/license_server/release_notes.html#30241
- JetBrains updated the the dependencies for log4j to version 2.16.0
=> Update JetBrains Floating license server version number

software/README.md
This PR corrects two errors in the software markdown table.  
One row had too few rows, and one had one too many.
=> Correct errors in software table column counts

software/README.md
version info is confusing, source url does not mention version < 10.8.0.
cisa url shows all versions are fixed (https://github.com/cisagov/log4j-affected-db)
-issued a new PR (old: 5abe41c) after column change-
=> updated ESRI: removed version info

software/README.md
We have been having external requests and expectations that this table should be up to date with the most recent advisory updates.
At the pace we are currently trying to handle these incidents from our side it is currently not feasible to manually maintain a list of affected products in multiple places in parallel, as this data gets quickly obsolete with the daily publications we have been making.
Therefore we propose to keep here only the links to the published advisories, so that Siemens costumers can always have the most up to date information.
In addition we provide a CSAF format that can be used for customers who wish to automatically parse the list of affected products.
=> Update data for Siemens products

software/README.md
All versions of Apache Kafka are vulnerable to CVE-2021-4104, but
mitigation steps are available.
Update status for CVE-2021-4104 to "Workaround".
Apache Kafka uses Log4j 1.2.17.
Update Log4j version to this exact version.
The list of [Apache Kafka Security Vulnerabilities] provides all
relevant information in a condensed form.
Replace the Kafka mailing list thread with the Apache Kafka Security
Vulnerabilities as source.
[Apache Kafka Security Vulnerabilities]: https://kafka.apache.org/cve-list
directory
=> Update Apache Kafka record

software/README.md
- Textual changes and headings.
- Added disclaimer
- Added clarity about the fact that the `Version` field is sometimes empty when `Fix` is present.
- Fixed some typo's.
=> Textual changes to the software list page.

scanning/README.md
- Added explanation of how to find log4j in java archives.
This does not seem to be common knowledge and is essential in finding vulnerable software.
- Noted limitations of some of the linked tools. The other tools do not have these limitations.
=> scanner Readme: Explain how to find log4j and note limitations

software/README.md
Updated existing eWon entry, to add fix for CVE-2021-45105
Added entry for HMS-Network to their Security Documents page
directory
=> Update eWon + Add entry for HMS-Networks

software/software_list_h.md
HCL BigFix Compliance is confirmed not vulnerable as per the updated KB article in source. 
removed extra " characters from other HCL BigFix lines
directory
=> Update HCL BigFix Compliance

scanning/README.md
Hi,
I wrote (yet) another file system scanner, which seems to be faster then the other available, attempting to be precise in version detection and exhaustive in identifying vulnerable instances.
- Identifies exact log4j version in the 2.x as well as 1.x range
- Detecting CVE-2021-44832, CVE-2021-44228, CVE-2021-45046, CVE-2021-45105, CVE-2021-4104
- Optionally fixing vulnerability by renaming JndiLookup class
Link: https://github.com/HynekPetrak/log4shell-finder
This pull requests adds it to the list of Scanning software.
=> Add log4shell-finder to scanning tools

software/software_list_b.md
Updated BioJava CVE-2021-45105 column to 'Fix' and replaced link with new release
=> Update BioJava Fix for CVE-2021-45105
