NCSC-NL/log4shell

software/README.md

And fix link in CAS section.
Thijs Kinkhorst
SURFcert

Add Shibboleth not affected

---

software/README.md

"Autonomous Identity" is the only affected product.
All other producs not affected.
Thijs Kinkhorst
SURFcert

Add ForgeRock affected

---

software/README.md

Add status for [Opencast](https://github.com/opencast/opencast) (see [source](https://github.com/opencast/opencast/security/advisories/GHSA-mf4f-j588-5xm8)).
This also fixes a spelling from Apero to Apereo.

Add Opencast Fix

---

software/README.md

Adding software Akamai = Siem Splunk Connector (log4j pinned to 2.13.3)

Akamai -Siem Splunk Connector vulnerable

---

software/README.md

See: https://www.wowza.com/docs/known-issues-with-wowza-streaming-engine#log4j2-cve

Add Wowza Streaming Engine to software list

---

software/README.md

Added USoft and Exact Synergy, discovered by manual scanning this morning. No vendor information available yet. Added screenshot as proof.

Added USoft and Exact Synergy

---

software/README.md

FME server is a geospatial ETL tool used by many government agencies internally.

Add FME Server to software list

---

software/README.md

Adding status for MongoDB. See [here ](https://www.mongodb.com/blog/post/log4shell-vulnerability-cve-2021-44228-and-mongodb)fore source.

Add MongoDB status to software list

---

software/README.md

added fortinet products from source: https://www.fortiguard.com/psirt/FG-IR-21-245

add-fortinet

---

README.md

This change makes the `README.md` more user-friendly.

make references to directory content in README.md clickable

---

software/README.md

this adds Websphere 8.5 and 9.0 information

added Websphere 8.5 and 9.0 fix info

---

software/README.md

Add FileCap to software-list

---

software/README.md

Zabbix Monitoring is NOT AFFECTED by the Log4j exploit

Update README.md with Zabbix Monitoring information

---

software/README.md

Add software under investigation by Dell

---

software/README.md

Added Moodle with source being one of the core developers.
https://moodle.org/mod/forum/discuss.php?d=429966
Status: not affected

Added Moodle

---

software/README.md

Add the software papercut versions NG and MF

Add PaperCut NG and MF

---

software/README.md

Reverts NCSC-NL/log4shell#103
Double entry.

Revert "Add PaperCut NG and MF"

---

software/README.md

Chef products were incorrectly listed here. They are not vulnerable. See the blog post in the source.
Signed-off-by: Tim Smith <tsmith@chef.io>

Mark Chef products as not vulnerable

---

software/README.md

Not vulnerable after investigation (see article).

Update Citrix Workspace app

---

software/README.md

Add synology DSM - not vuln

---

software/README.md

Add postgres jdbc - not vuln

---

software/README.md

Change to correct name (Check Point, not Checkpoint)
Set to All versions
Give a shorter link to the SK

Set Check Point status better

---

software/README.md

Add Mitel to software list

---

software/README.md

Update status Citrix

---

software/README.md

Instead of the forum link, there is a information page on the website with an official alert now.

Update ESET source

---

software/README.md

Update Datev to vuln

---

software/README.md

https://www.mailstore.com/en/blog/mailstore-affected-by-log4shell/

MailStore -> not vuln

---

software/README.md

Although with limited impact, Arduino IDE is also impacted by the use of this library. Fixes have been provided as a nightly built and is set to release before Dec, 18th

Added Arduino IDE

---

software/README.md

Correction Mitel

---

software/README.md

Atlassian BitBucket on prem workaround

---

software/README.md

Update Cisco NSO from advisory

---

software/README.md

Updated to add SailpointIQ 8.0

---

software/README.md

Added Owncloud (Filesharing) as Not Vuln to README

Added Owncloud (Filesharing) as Not Vuln to README

---

mitigation/README.md

Hi,
We're lacking mitigation on web-server level although there are some techniques in the works already. Was not sure where it belongs, so decided to add a whole new section in mitigation/README.md

mitigation: add web-server section including Nginx

---

software/README.md

Added Mirantis software

---

software/README.md

updated couchbase version

---

software/README.md

Added Lancom Systems and Liongard

Added Lancom Systems and Liongard

---

software/README.md

Remove duplicate igel

---

software/README.md

Elastic fixed

---

software/README.md

Added info about Jedis

---

software/README.md

Added estos andVulnerable/Investigation Software of Unify

 Added estos andVulnerable/Investigation Software of Unify

---

software/README.md

Collapsing HCL Compliance Investigating lines into a single Workaround line.
Adding version to HCL BigFix Inventory in addition to the Workaround.
directory

Update entries for HCL BigFix with latest updates

---

software/README.md

Cisco Adaptive Security Appliance

---

software/README.md

Added LogZilla

---

software/README.md

This PR aligns Nutanix products with version v1.6 of our security advisory 23, which will be updated shortly

nutanix: update to align with SA23 v1.6

---

software/README.md

Add CODESYS products

---

software/README.md

Updated HCL BigFix Compliance with  version range and updated URL
directory

Updated HCL BigFix Compliance with latest

---

software/README.md

Update with Tenable information

---

software/README.md

Added info Lansweeper
directory

Added Lansweeper

---

software/README.md

Add Y Soft Product

---

software/README.md

Add Sprecher Automation products

---

software/README.md

Adding Alertus Server

---

software/README.md

Updated `Packet Trace Warehouse` status
Source: https://supportkb.riverbed.com/support/index?page=content&id=S35645&actp=LIST_RECENT

Updated Riverbed status

---

.github/pull_request_template.md

Attempt at making open PR list better usable

---

software/README.md

Add Pexip products to software list

---

software/README.md

OCLC (major library systems vendor) declared all systems fixed/mitigated on https://oc.lc/status (and confirmed in private correspondence)
Thijs Kinkhorst
SURFcert

Add OCLC all products

---

software/README.md

update Vmware HCX

---

software/README.md

Adds alphabetic links for quick jump

---

software/README.md

Add Evolveum midPoint IDM

---

software/README.md

Adding additional information to existing entries.
Added affected versions to Ruckus items and added links to PDF and Text document containing more information. Sign-in required.

Added Ruckus version details and link to more info

---

software/README.md

https://www.tripwire.com/log4j

add tripwire to software list

---

software/README.md

Info from direct correspondence with vendor, no public statements yet

Add 7signal sapphire

---

software/README.md

Exact toegevoegd. NL statement + EN statement
directory

Toegevoegd Exact

---

software/README.md

Exivity does not ship with any Java components. See our announcement at https://exivity.atlassian.net/servicedesk/customer/portal/2.
directory

Added Exivity note

---

software/README.md

Add Meinberg products

---

software/README.md

Add Hitachi Energy statement

---

software/README.md

BeyondTrust software was never affected by this vulnerability as there is no possible attack vector to exploit it from either product. The removal of the library and environment variable patch were only proactive measures for added security. The security bulletin will be updated shortly.

Removed BeyondTrust from supplier list

---

software/README.md

Add Yellowfin Software

---

software/README.md

Add LiveAction affected/fixed products
directory

Add LiveAction affected/fixed products

---

scanning/README.md

This PR fixes the sorting of the scanning/README.md along with clarification of a few entries

scanning/README.md - Fixed

---

software/README.md

Add Wildfly

---

software/README.md

Netgate / pfSense - not vulnerable
Link to support forum where moderators confirm not vuln (no java in product)

Add Netgate / pfSense

---

software/README.md

Kofax Robotic Process Automation (RPA) & Robot File System (RFS)

---

software/README.md

Add Devolutions to vendors

---

software/README.md

Status: Not Vuln
Link: https://www.qnap.com/en-uk/security-advisory/qsa-21-58
Literally just added the OS some link as other QNAP OS.

Added QNAP QES operating system as non vuln

---

software/README.md

Added Infoblox response/information regarding Log4j.
directory

Added Infoblox software

---

software/README.md

fixed layout

---

software/README.md

Update Advanced Authentication and fix source links based on new information.
directory

Update Advanced Authentication and fix NetIQ source links

---

software/README.md

- Status: DrawIO not vulnerable
- Version: All versions of DrawIO
- Links: https://github.com/jgraph/drawio/issues/2490

Update README - DrawIO added

---

software/README.md

Add Zyxel Devices

---

software/README.md

https://support.zendesk.com/hc/en-us/articles/4413583476122-2021-12-13-Security-Advisory-Apache-Log4j-CVE-2021-44228-
saas
directory

Adding Zendesk

---

software/README.md

Added the following medical systems:
- Philips IntelliSpace Precision Medicine
- Philips IntelliBridge Enterprise
- Philips Tasy EMR
- Philips ISPACS
- Philips RIS Clinic
- Philips VuePACS
- Alphatron Custo diagnostics
- Alphatron JiveX
- Alphatron Zorgbericht
- Alphatron AMiSconnect

Medical systems of Philips and Alphatron

---

software/README.md

Fix markup source SAP

---

software/README.md

Statement links to further details in customer portal

Add AFAS statement not vuln

---

software/README.md

Add Check_MK

---

software/README.md

Adding device information for the Meraki product line, including links to the Cisco doucmentation.

Meraki Product Line Update

---

software/README.md

Update Ubiquiti Unifi Network Application (CVE-2021-45046)

---

software/README.md

Added B. Braun

---

software/README.md

Two Apache products were mis-sorted
Thijs Kinkhorst / SURFcert

Fix sorting of Apache products

---

software/README.md

Add information about JetBrains products

---

software/README.md

Added Sitecore

---

software/README.md

Add link to ManageEngine ADAudit Plus workaround

ManageEngine ADAudit Plus workaround

---

software/README.md

Added Grafana

---

software/README.md

Add vulnerable Clavister products

---

software/README.md

Revised Trend Micro Products/Services with latest information

---

software/README.md

Added Plex Media Server

---

software/README.md

Add TOPdesk products to software

---

software/README.md

updated Siemens products

---

software/README.md

SAP S/4 HANA

---

software/README.md

Note that external libraries may still have Java dependencies which Mathworks doesn't control.

Added Mathworks MATLAB products

---

software/README.md

Added IBM Cloud Object storage

---

software/README.md

Email Security is impacted. NSM and Analytics are still under review. Other products are not vulnerable.

Update Sonicwall products

---

software/README.md

AVM routers and devices update

---

software/README.md

Adding Apache NiFi based on https://issues.apache.org/jira/browse/NIFI-9474

Adding Apache NiFi

---

software/README.md

Add Bender GmbH und Co. KG

---

software/README.md

Was first Not vulnerable but now is vulnerable.
directory

Changed Cisco CSPC status

---

software/README.md

No fix yet, workaround verified
directory

Added Autopsy

---

software/README.md

Added Appian

---

software/README.md

https://www.influxdata.com/blog/apache-log4j-vulnerability-cve-2021-44228/

Added InfluxDB

---

software/README.md

No Fix yet, Manual bypass seems to work fine : https://github.com/apache/jmeter/pull/680#issuecomment-993204248
directory

Add Apache JMeter

---

software/README.md

Update software vendors with CaseWare products

---

software/README.md

Add IBM DB2 Server

---

software/README.md

Added Imprivata

---

software/README.md

Added Supermicro's products not vulnerable and vulnerable

Added Supermicro’s response

---

software/README.md

Added InterSystems products

---

software/README.md

Link requires login to support portal
directory

Added Quest KACE SMA

---

software/README.md

Hotfixes for Cisco ISE are expected, list updated from source https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-apache-log4j-qRuKNEbd

Updated Cisco ISE with expected fix date

---

software/README.md

Add Phoenix Contact products

---

software/README.md

Add TRUMPF products

---

software/README.md

- Added official advisory on ColdFusion and expected patch date
- Added official general statement by Adobe as under investigation
directory

Updated Adobe

---

software/README.md

Added ABB advisory for log4shell 

---

software/README.md

Add Tailscale

---

software/README.md

Added a statement regarding the products of Tesorion and Compumatica.
directory

Added Tesorion and Compumatica product statement

---

software/README.md

Added Rocket Chat

---

software/README.md

Update Schneider Electric products

---

software/README.md

Add Ghisler Total Commander as non vuln

---

software/README.md

Fixed in FileCap Server version 5.1.1.
Added FileCap Plugins, not vulnerable.

Update FileCap Server and Added FileCap plugins

---

software/README.md

Add Apache HBase

---

software/README.md

Add Moxa statement

---

software/README.md

Add Hitachi Energy products (UNEM and FOXMAN-UN)

---

software/README.md

Update Trend Micro (fix typos in mobile products)

---

software/README.md

Update JetBrains products by specifying all tools

---

software/README.md

Added Infoland systems

---

software/README.md

Added Fujitsu ServerView Operations Manager and Update Manager as vulnerable according to Fujitsu's Security Notice:
https://support.ts.fujitsu.com/ProductSecurity/content/Fujitsu-PSIRT-PSS-IS-2021-121000-Security-Notice-SF.pdf

Added Fujitsu ServerView

---

software/README.md

Added Redgate/Flyway

---

software/README.md

Added ESET Secure Authentication

---

software/README.md

Added vulnerable HPE products listed at https://support.hpe.com/hpesc/public/docDisplay?docId=hpesbgn04215en_us.

Added vulnerable HPE products

---

software/README.md

Added Red Hat Virtualization 4 from issue #417

Add Red Hat Virtualization 4

---

software/README.md

Added Stackstate systems

---

software/README.md

Added DocuShare products listed at https://security.business.xerox.com/wp-content/uploads/2021/12/DocuShare-Security-Bulletin-XRX21-022-for-CVE-2021-44228.pdf.

Added Xerox DocuShare

---

software/README.md

Added VMware Skyline Collector virtual appliance from issue #179

Add VMware Skyline Collector virtual appliance

---

software/README.md

Add AOMEI all products as not vuln

---

software/README.md

Add Polycom

---

hunting/Log4j-Microsoft-Defender.md
hunting/README.md
software/README.md

For contributions in `Hunting/`:
Added Markdown file for "Microsoft 365 Defender advanced hunting queries" and updated the README.md with the link to the Log4-Microsoft-Defender.md file in the generic Hunting readme.md file

Added Microsoft 365 Defender advanced hunting queries

---

software/README.md

Added Dräger, Enovation and ResMed

---

software/README.md

> Links: make sure you link to a public statement by the developer.
Is this PR coming from us good enough, or do we need to have a statement on one of our own properties?

note powerdns products as not vulnerable

---

software/README.md

Added BlackBerry from issue #499

Add BlackBerry

---

software/README.md

Nieuwe poging omdat bij de vorige pull blijkbaar een andere wijziging werd overschreven.
directory

Added Draytek

---

mitigation/README.md

I noticed the blog post of AWS was missing and could be very valuable for others.

Add blog post by AWS to the list of mitigations

---

mitigation/README.md

Secure2me Network Intrusion Detection

---

software/README.md

Add Axis os not vuln

---

software/README.md

Add Dbeaver

---

software/README.md

Added Supplier ’Zscaker', which is cloud security vendor.
I checked the following.
directory

Add Supplier 'Zscaler' 

---

software/README.md

Added Ahsay Backup from issue #153

Add Ahsay Backup

---

software/README.md

Add entry for Catalogic Software CloudCasa to software/README.md

Add CloudCasa

---

software/README.md

Added dotCMS Hybrid Content Management System from issue #528

Add dotCMS Hybrid Content Management System

---

software/README.md

Add Device42

---

software/README.md

Add Variphy

---

software/README.md

Add Yenlo Connext WSO2 Managed Cloud to Software list
directory

Add Yenlo Connext WSO2 Managed Cloud

---

software/README.md

Added Wibu systems codemeter advisory.
[Source](https://cdn.wibu.com/fileadmin/wibu_downloads/security_advisories/Advisory_WIBU-211213-01.pdf )
directory

Added Wibu systems codemeter advisory.

---

software/README.md

Add Vectra (all products) to software list. [Source](https://support.vectra.ai/s/article/KB-VS-1568).
--- 
directory

Add Vectra

---

software/README.md

Added Apache Guacamole as not vulnerable

Added Apache Guacamole

---

software/README.md

Add PDQ Deploy and PDQ inventory status

---

software/README.md

Update some packages from Red Hat with the latest info on https://access.redhat.com/security/cve/cve-2021-44228
directory

Several updates for Red Hat products/packages

---

software/README.md

Add SeaGull Scientific Bartender

---

software/README.md

Add Abbott

---

software/README.md

Typo Akamai product

---

software/README.md

Add Ivanti Xtraction

---

software/README.md

Add LogRhythm SIEM

---

software/README.md

Add Kofax KCM and Capture
directory

Add Kofax KCM and Capture to software-list

---

software/README.md

Added Accruent from issue #319 and their other products

Add Accruent

---

software/README.md

Adjusting versions with available fix for Mitel MiCollab

Correct Mitel MiCollab versioning

---

software/README.md

Add SOS(Berlin) Jobscheduler

---

software/README.md

Added Enfocus products.
Statement here:
https://enfocus-community.force.com/customers/s/article/Are-the-Enfocus-products-impacted-by-the-log4j-security-vulnerability?language=en_US

Add Enfocus Products

---

software/README.md

Add SecurityHive products

---

software/README.md

Add Tools4ever/HelloID

---

software/README.md

Carbon Black is a VMWare Product and already listed under Vmware
directory

Cleanup Carbon black

---

software/README.md

Add PTC/Windchill PDMLink

---

software/README.md

This fixes both points of https://github.com/NCSC-NL/log4shell/issues/497
Sorry for the large number of commits for this little change.

Fixed formatting in software/README.md

---

hunting/README.md

This fixes https://github.com/NCSC-NL/log4shell/issues/579 and provides a better overview in the future once more hunting queries are shared
Also fixed the sorting

Added table to hunting/README.md

---

software/README.md

Added confuent info according to https://support.confluent.io/hc/en-us/articles/4412615410580-CVE-2021-44228-log4j2-vulnerability
This fixes https://github.com/NCSC-NL/log4shell/issues/446
====================================
directory

Add Confluent

---

software/README.md

Add TP-Link Omada SDN

---

software/README.md

Added bluemind, source : Twitter : https://twitter.com/bluemind/status/1470379923034578946?s=20
directory

Add Bluemind

---

software/README.md

Update Siemens products after SSA-661247 V1.3 and SSA-714170 V1.0

---

software/README.md

Updated USoft products

---

software/README.md

Sorted the list 
Stated on the site OneConnect is listed under NOT affected

Updated Clavister products

---

software/README.md

I also sorted alphabetically MISP and MONARC

Add Macrium Software

---

software/README.md

Update Pega Platform

---

software/README.md

Add glpi-project/glpi

---

software/README.md

HPE 3PAR Service Processor fixed in version 5.0.9.2
Release notes https://support.hpe.com/hpesc/public/docDisplay?docLocale=en_US&docId=a00002915en_us
directory

Fix: HPE/3PAR Service Processor

---

software/README.md

Added Decos solution to list (7 entries) to software/README.md
Signed-off-by: Alain van Hanegem - a.vanhanegem@decos.com
For contributions in software/:
PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
Status: please select a value from the status table at the top
Version: Status Vulnerable / Workaround? -> List vulnerable versions.
Status Fix? -> List fixed versions.
Links: make sure you link to a public statement by the developer.
Alternatively, include and link a file in the software/vendor-statements/
directory
Please mind the sorting

Add Decos solutions to list with status/detail

---

software/README.md

+ Add the Coveo statement about Log4Shell to software/README.md
Signed-off-by: Jean-Philippe Lachance <jplachance@coveo.com>
directory

Add the Coveo statement about Log4Shell

---

software/README.md

Add eG Innovations to Table

---

software/README.md

Update Akamai Siem Splunk Connector

---

software/README.md

Move Confluence entries (=Product name) to Atlassian (Vendor Name) in section "A"
directory

Move Confluence entries (Product name)

---

software/README.md

Added products from vendor Pure Storage, Cloud Block Store, FlashArray, FlashBlade en VM analytics collector

Added Pure Storage

---

software/README.md

Added Boston Scientific, Canon, Johnson Controls, Zeiss, Vyaire

---

software/README.md

Updated based on [V5][V6] in https://aws.amazon.com/jp/security/security-bulletins/AWS-2021-006/ . Unnecessarily verbose notes were cleaned up.
directory

Update AWS products

---

software/README.md

Updated the splunk entries which received a fix.
directory

Splunk entries updated with latest versions

---

software/README.md

Correct spelling of ColdFusion, marked "Fix" with link

---

scanning/README.md

Update README.md - add Cyberreason logout4shell

---

software/README.md

- Removed some of the duplicated items
- Removed the Lenovo in front at some of the product names

Updated Lenovo

---

software/README.md

Added their remaining products from their latest bulletin post

Update the other Xerox products

---

software/README.md

Updated Unifi information

---

software/README.md

Updated TOPdesk

---

software/README.md

Updated johnson controls

---

software/README.md

- still claimed not vulnerable by the vendor
- latest version removes log4j just in case
directory

the hive - update

---

software/README.md

Added IBM information

---

software/README.md

Update: Enfocus to reflect non vulnerable on CVE-columns

Update: Enfocus to reflect CVE-columns

---

software/README.md

Fixed in version 3.00.72.1 https://support.hpe.com/hpesc/public/docDisplay?docLocale=en_US&docId=hpesbgn04224en_us
directory

Fix: HPE/Real Time Management System (RTMS)

---

software/README.md

Sort enfocus alphabetically

---

software/README.md

Add Belden's statement about Hirschmann brand products

---

tools/log4shell_softwarelist/softwarelist_parser.py

softwarelist_parser.py gives a out of range error when running. This fixes it.

fix for softwarelist_parser.py

---

software/README.md

Added SAP Hana Cockpit, 
Modified SAP XSA, Fix for CVE-2021-45046
directory

Update README.md, added SAP Hana Cockpit

---

software/README.md

Fixes are available for impacted Panorama appliances. Updates around related vulnerability CVE-2021-45105

Update Palo Alto

---

software/HOWTO.pr-review.md

First attempt at writing some documentation based on our review practice in the past week. Changes / feedback welcome.

Add review documentation

---

software/README.md

Update the status for CVE-2021-45046 and CVE-2021-45105

Update Nulab products

---

software/README.md

Changed Status CVE-2021-45046 to Fix and Status CVE-2021-45105 to Vulnerable

Update BioJava Status

---

software/README.md

FlexNet Publisher License manager (64-bits) is vulnerable, see https://community.flexera.com/t5/FlexNet-Publisher-Knowledge-Base/CVE-2021-44228-amp-CVE-2021-45105-Log4j-vulnerability-impact-on/ta-p/217384 for more information
directory

Added FlexNet Publisher license manager

---

software/README.md

Updated status of products and added products.
directory

 Updatet Johnson Controls

---

software/README.md

Update NVIDIA, Vyaire medical

---

software/README.md

New versions Apache Log4j 2

---

scanning/README.md

Adding local Qualys scanner that checks for multiple CVE's

Add Qualys Log4Jscanwin 

---

software/README.md

Update Johnson Controls

---

software/README.md

Adding JavaMelody

---

software/README.md

Remove table error at B

---

.github/check_valid.py
.github/workflows/check-software-diff.yml

New GH Action to check format of table during PRs.

Check softwarelist format

---

software/README.md

Fix table error at Johnson Controls

fix table error

---

software/README.md

Added mutiple suppliers

---

.github/workflows/check-software-diff.yml

Fix checker with direct download

---

.github/workflows/check-software-diff.yml

insert missing --no-index

---

software/README.md

Add Spectralink

---

.github/workflows/check-software-diff.yml

As there are splitted files, the checker was updated.

Address updated repo stucture

---

software/software_list_w.md

Added Wallix product

---

software/software_list_a.md

Update of alfresco entry

---

software/software_list_o.md

 Add Open Text Content Server and ECM

---

software/software_list_u.md

Merged duplicate entries (Unifi Network Application = Unifi Network Controller) and updated CVE-2021-45046, CVE-2021-45105 & CVE-2021-44832 per status updates of Team Ubiquiti on the Ubiquiti Security Advisory Bulletin 023

Updated Ubiquiti software list

---

software/software_list_a.md

Software list A - Sorting

---

software/software_list_b.md

Software list B - sorting

---

software/software_list_c.md

Software list C - sorting

---

software/software_list_e.md

Software list E - sorting

---

software/software_list_f.md

Software list F - sorting

---

software/software_list_j.md

Software list J - sorting

---

software/software_list_k.md

Software list K - sorting

---

software/software_list_l.md

Software list L - sorting

---

software/software_list_m.md

Software list M - sorting

---

software/software_list_n.md

Software list N - sorting

---

software/software_list_p.md

Software list P - sorting

---

software/software_list_q.md

Software list Q - sorting

---

software/software_list_t.md

Software list T - sorting

---

software/software_list_u.md

Software list U - sorting

---

software/software_list_v.md

Software list V - sorting

---

software/software_list_w.md

Software list W - sorting

---

software/software_list_y.md

Software list Y - sorting

---

software/software_list_b.md

Added a few versions of three products.
directory

updatet Boston Scientific information

---

software/software_list_h.md

Fixed Status to follow naming convention

---

scanning/README.md

- [X ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
directory

Add scanner yannart/log4shell-scanner-rs

---

software/software_list_c.md

Correcting Cisco CESM from (Fix | Investigation) to (Not vuln | Not vuln) according to https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-apache-log4j-qRuKNEbd
directory

Anssi cvp patch 43 cisco correction cesm

---

software/software_list_o.md

Add Ovarro products

---

software/software_list_p.md

Cloud services were either not affected or are fixed now. Affected services have been checked and no exploit was observed.

Update Phoenix Contact status

---

software/software_list_s.md

Added Smiths Medical

---

software/software_list_p.md

Add info for Procentec products

---

software/software_list_r.md

Updated Rockwell products

---

software/software_list_a.md

Duplicate can be found under S
directory

removed duplicate Schneider Electric
